# Generated by Django 4.2.7 on 2024-05-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='documento',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='docente_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombre_completo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='docente',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='docente_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
