# Generated by Django 4.2.7 on 2024-05-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_alter_docente_correo_alter_docente_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='password',
            field=models.CharField(default='12345', max_length=20),
        ),
    ]
