# Generated by Django 4.2.7 on 2024-05-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0004_alter_estudiante_options_alter_estudiante_managers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adivinanza',
            new_name='Adivinanzas',
        ),
        migrations.RenameModel(
            old_name='Pregunta',
            new_name='Preguntas',
        ),
    ]
