# Generated by Django 4.2.7 on 2024-05-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0005_rename_adivinanza_adivinanzas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='codCurso',
            field=models.CharField(default='12345', max_length=25),
            preserve_default=False,
        ),
    ]
