# Generated by Django 4.2.7 on 2024-05-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0006_curso_codcurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='id',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='codCalificacion',
            field=models.CharField(default='12345', max_length=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
