# Generated by Django 4.2.7 on 2024-05-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0008_puntuacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('enlace_1', models.URLField()),
                ('enlace_2', models.URLField()),
            ],
        ),
    ]
